name: ci
on: 
  pull_request:
    # types: [opened,edited]
    branches:
      - develop
      - github_actions_pr_test
      - feature/*
      - hotfix/*
      - github_actions

jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: npx eslint . --fix
      - run: npx pretty-quick .

