name: ci
on: [push]
jobs: 
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/steup-node@v3
      with:
        node-version: '14'
      -run : npm install 
      -run : npm run prepare
      -run : npx eslint . --fix